/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as ContinueWatchingIndexRouteImport } from './routes/continue-watching/index'
import { Route as PlayerIdRouteImport } from './routes/player/$id'
import { Route as AuthSocialSignupRouteImport } from './routes/_auth/social-signup'
import { Route as AuthSocialCallbackRouteImport } from './routes/_auth/social-callback'
import { Route as ProfileSettingsIndexRouteImport } from './routes/profile/settings/index'
import { Route as ProfileCollectionIndexRouteImport } from './routes/profile/collection/index'
import { Route as ProfileCollectionSlugRouteImport } from './routes/profile/collection/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueWatchingIndexRoute = ContinueWatchingIndexRouteImport.update({
  id: '/continue-watching/',
  path: '/continue-watching/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSocialSignupRoute = AuthSocialSignupRouteImport.update({
  id: '/_auth/social-signup',
  path: '/social-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSocialCallbackRoute = AuthSocialCallbackRouteImport.update({
  id: '/_auth/social-callback',
  path: '/social-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsIndexRoute = ProfileSettingsIndexRouteImport.update({
  id: '/profile/settings/',
  path: '/profile/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCollectionIndexRoute = ProfileCollectionIndexRouteImport.update({
  id: '/profile/collection/',
  path: '/profile/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCollectionSlugRoute = ProfileCollectionSlugRouteImport.update({
  id: '/profile/collection/$slug',
  path: '/profile/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/social-callback': typeof AuthSocialCallbackRoute
  '/social-signup': typeof AuthSocialSignupRoute
  '/player/$id': typeof PlayerIdRoute
  '/continue-watching': typeof ContinueWatchingIndexRoute
  '/download': typeof DownloadIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/collection/$slug': typeof ProfileCollectionSlugRoute
  '/profile/collection': typeof ProfileCollectionIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/social-callback': typeof AuthSocialCallbackRoute
  '/social-signup': typeof AuthSocialSignupRoute
  '/player/$id': typeof PlayerIdRoute
  '/continue-watching': typeof ContinueWatchingIndexRoute
  '/download': typeof DownloadIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/collection/$slug': typeof ProfileCollectionSlugRoute
  '/profile/collection': typeof ProfileCollectionIndexRoute
  '/profile/settings': typeof ProfileSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/social-callback': typeof AuthSocialCallbackRoute
  '/_auth/social-signup': typeof AuthSocialSignupRoute
  '/player/$id': typeof PlayerIdRoute
  '/continue-watching/': typeof ContinueWatchingIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/collection/$slug': typeof ProfileCollectionSlugRoute
  '/profile/collection/': typeof ProfileCollectionIndexRoute
  '/profile/settings/': typeof ProfileSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/social-callback'
    | '/social-signup'
    | '/player/$id'
    | '/continue-watching'
    | '/download'
    | '/explore'
    | '/home'
    | '/profile'
    | '/profile/collection/$slug'
    | '/profile/collection'
    | '/profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/social-callback'
    | '/social-signup'
    | '/player/$id'
    | '/continue-watching'
    | '/download'
    | '/explore'
    | '/home'
    | '/profile'
    | '/profile/collection/$slug'
    | '/profile/collection'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth/social-callback'
    | '/_auth/social-signup'
    | '/player/$id'
    | '/continue-watching/'
    | '/download/'
    | '/explore/'
    | '/home/'
    | '/profile/'
    | '/profile/collection/$slug'
    | '/profile/collection/'
    | '/profile/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSocialCallbackRoute: typeof AuthSocialCallbackRoute
  AuthSocialSignupRoute: typeof AuthSocialSignupRoute
  PlayerIdRoute: typeof PlayerIdRoute
  ContinueWatchingIndexRoute: typeof ContinueWatchingIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileCollectionSlugRoute: typeof ProfileCollectionSlugRoute
  ProfileCollectionIndexRoute: typeof ProfileCollectionIndexRoute
  ProfileSettingsIndexRoute: typeof ProfileSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue-watching/': {
      id: '/continue-watching/'
      path: '/continue-watching'
      fullPath: '/continue-watching'
      preLoaderRoute: typeof ContinueWatchingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/social-signup': {
      id: '/_auth/social-signup'
      path: '/social-signup'
      fullPath: '/social-signup'
      preLoaderRoute: typeof AuthSocialSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/social-callback': {
      id: '/_auth/social-callback'
      path: '/social-callback'
      fullPath: '/social-callback'
      preLoaderRoute: typeof AuthSocialCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings/': {
      id: '/profile/settings/'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/collection/': {
      id: '/profile/collection/'
      path: '/profile/collection'
      fullPath: '/profile/collection'
      preLoaderRoute: typeof ProfileCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/collection/$slug': {
      id: '/profile/collection/$slug'
      path: '/profile/collection/$slug'
      fullPath: '/profile/collection/$slug'
      preLoaderRoute: typeof ProfileCollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSocialCallbackRoute: AuthSocialCallbackRoute,
  AuthSocialSignupRoute: AuthSocialSignupRoute,
  PlayerIdRoute: PlayerIdRoute,
  ContinueWatchingIndexRoute: ContinueWatchingIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileCollectionSlugRoute: ProfileCollectionSlugRoute,
  ProfileCollectionIndexRoute: ProfileCollectionIndexRoute,
  ProfileSettingsIndexRoute: ProfileSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
