/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
<<<<<<< HEAD
import { Route as ProfileCollectionIndexRouteImport } from './routes/profile/collection/index'
import { Route as ProfileCollectionSlugRouteImport } from './routes/profile/collection/$slug'
=======
import { Route as PlayerIdRouteImport } from './routes/player/$id'
>>>>>>> b8f5ce9 (Resolve Conflict)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ProfileCollectionIndexRoute = ProfileCollectionIndexRouteImport.update({
  id: '/profile/collection/',
  path: '/profile/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCollectionSlugRoute = ProfileCollectionSlugRouteImport.update({
  id: '/profile/collection/$slug',
  path: '/profile/collection/$slug',
=======
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
>>>>>>> b8f5ce9 (Resolve Conflict)
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player/$id': typeof PlayerIdRoute
  '/download': typeof DownloadIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/collection/$slug': typeof ProfileCollectionSlugRoute
  '/profile/collection': typeof ProfileCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/$id': typeof PlayerIdRoute
  '/download': typeof DownloadIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/home': typeof HomeIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/collection/$slug': typeof ProfileCollectionSlugRoute
  '/profile/collection': typeof ProfileCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player/$id': typeof PlayerIdRoute
  '/download/': typeof DownloadIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/home/': typeof HomeIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/collection/$slug': typeof ProfileCollectionSlugRoute
  '/profile/collection/': typeof ProfileCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
<<<<<<< HEAD
=======
    | '/player/$id'
>>>>>>> b8f5ce9 (Resolve Conflict)
    | '/download'
    | '/explore'
    | '/home'
    | '/profile'
<<<<<<< HEAD
    | '/profile/collection/$slug'
    | '/profile/collection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/explore'
    | '/home'
    | '/profile'
    | '/profile/collection/$slug'
    | '/profile/collection'
  id:
    | '__root__'
    | '/'
=======
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/player/$id' | '/download' | '/explore' | '/home' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/player/$id'
>>>>>>> b8f5ce9 (Resolve Conflict)
    | '/download/'
    | '/explore/'
    | '/home/'
    | '/profile/'
<<<<<<< HEAD
    | '/profile/collection/$slug'
    | '/profile/collection/'
=======
>>>>>>> b8f5ce9 (Resolve Conflict)
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerIdRoute: typeof PlayerIdRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileCollectionSlugRoute: typeof ProfileCollectionSlugRoute
  ProfileCollectionIndexRoute: typeof ProfileCollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/profile/collection/': {
      id: '/profile/collection/'
      path: '/profile/collection'
      fullPath: '/profile/collection'
      preLoaderRoute: typeof ProfileCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/collection/$slug': {
      id: '/profile/collection/$slug'
      path: '/profile/collection/$slug'
      fullPath: '/profile/collection/$slug'
      preLoaderRoute: typeof ProfileCollectionSlugRouteImport
=======
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
>>>>>>> b8f5ce9 (Resolve Conflict)
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerIdRoute: PlayerIdRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileCollectionSlugRoute: ProfileCollectionSlugRoute,
  ProfileCollectionIndexRoute: ProfileCollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
